# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newcase.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(577, 394)
        self.btnok = QtWidgets.QPushButton(Dialog)
        self.btnok.setGeometry(QtCore.QRect(300, 280, 75, 30))
        self.btnok.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnok.setFont(font)
        self.btnok.setObjectName("btnok")
        self.btncancel = QtWidgets.QPushButton(Dialog)
        self.btncancel.setGeometry(QtCore.QRect(420, 280, 75, 30))
        self.btncancel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btncancel.setFont(font)
        self.btncancel.setObjectName("btncancel")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 60, 551, 181))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.btnmeshpath = QtWidgets.QPushButton(self.widget)
        self.btnmeshpath.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnmeshpath.setFont(font)
        self.btnmeshpath.setObjectName("btnmeshpath")
        self.gridLayout.addWidget(self.btnmeshpath, 1, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.btnfilepath = QtWidgets.QPushButton(self.widget)
        self.btnfilepath.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnfilepath.setFont(font)
        self.btnfilepath.setObjectName("btnfilepath")
        self.gridLayout.addWidget(self.btnfilepath, 0, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnok.setText(_translate("Dialog", "确定"))
        self.btncancel.setText(_translate("Dialog", "取消"))
        self.label_3.setText(_translate("Dialog", "网格来源"))
        self.btnmeshpath.setText(_translate("Dialog", "浏览"))
        self.btnfilepath.setText(_translate("Dialog", "浏览"))
        self.label.setText(_translate("Dialog", "地址"))
