# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slicewin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.btnok = QtWidgets.QPushButton(Dialog)
        self.btnok.setGeometry(QtCore.QRect(140, 210, 91, 31))
        self.btnok.setObjectName("btnok")
        self.btncancel = QtWidgets.QPushButton(Dialog)
        self.btncancel.setGeometry(QtCore.QRect(260, 210, 91, 31))
        self.btncancel.setObjectName("btncancel")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(82, 70, 251, 68))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelnormal = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelnormal.sizePolicy().hasHeightForWidth())
        self.labelnormal.setSizePolicy(sizePolicy)
        self.labelnormal.setMinimumSize(QtCore.QSize(81, 0))
        self.labelnormal.setMaximumSize(QtCore.QSize(110, 16))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(11)
        self.labelnormal.setFont(font)
        self.labelnormal.setObjectName("labelnormal")
        self.gridLayout.addWidget(self.labelnormal, 1, 0, 1, 1)
        self.labelpoint = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelpoint.sizePolicy().hasHeightForWidth())
        self.labelpoint.setSizePolicy(sizePolicy)
        self.labelpoint.setMinimumSize(QtCore.QSize(100, 0))
        self.labelpoint.setMaximumSize(QtCore.QSize(110, 16))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(11)
        self.labelpoint.setFont(font)
        self.labelpoint.setObjectName("labelpoint")
        self.gridLayout.addWidget(self.labelpoint, 0, 0, 1, 1)
        self.textpoint = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textpoint.sizePolicy().hasHeightForWidth())
        self.textpoint.setSizePolicy(sizePolicy)
        self.textpoint.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textpoint.setFont(font)
        self.textpoint.setText("")
        self.textpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.textpoint.setObjectName("textpoint")
        self.gridLayout.addWidget(self.textpoint, 0, 2, 1, 1)
        self.textnormal = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textnormal.sizePolicy().hasHeightForWidth())
        self.textnormal.setSizePolicy(sizePolicy)
        self.textnormal.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textnormal.setFont(font)
        self.textnormal.setText("")
        self.textnormal.setAlignment(QtCore.Qt.AlignCenter)
        self.textnormal.setObjectName("textnormal")
        self.gridLayout.addWidget(self.textnormal, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "切片设置"))
        self.btnok.setText(_translate("Dialog", "确认"))
        self.btncancel.setText(_translate("Dialog", "取消"))
        self.labelnormal.setText(_translate("Dialog", "平面法向量"))
        self.labelpoint.setText(_translate("Dialog", "平面中点坐标"))
